### ISSUE TITLE
Easier way to find video ID

### ISSUE THREAD

**Issue by vulpinefoxxo** [zoony1337/Triller-View-Bot#1]
Step 1: go to your video through the shortlink (https://v.triller.co/...)
Step 2: find a div, its class should be videoElem
Inside the div, there is a data-id, which is what you need

Edit: also it looks like you can get IP banned for a while

**Comment by zoony1337** [comment]
Yeah, I noticed it was in page source a couple hours after uploading the repo but have yet not been arsed updating it. I developed a simple one-liner that parses video IDs from video URLs for my community though — on Discord.
